builders:
  mapper:
    import: "package:smartstruct_generator/builder.dart"
    builder_factories: ["smartstructBuilder"]
    build_extensions: { ".dart": ["mapper.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
